const namesSFW = [
    "Abel Auboisdormant",
    "Adam Troijours",
    "Adrienne Kepoura",
    "Adémar Monoto",
    "Adémar Okardetour",
    "Adémar Pas El Kal",
    "Agathe Zeublouse",
    "Ahmed Épan",
    "Akim Embett",
    "Alain Di",
    "Alain Provist",
    "Alain Térieur",
    "Alain Verse",
    "Alban Bou",
    "Albert Ichon",
    "Aldo Berman",
    "Alex Ception",
    "Alex Cité",
    "Alex Pyration",
    "Alex Térieur",
    "Alfred Ezéfor",
    "Ali Gator",
    "Ali Mentation",
    "Aline Éha",
    "Allan Oi",
    "Alonzo Balmaské",
    "Alphonse Danlmur",
    "Alphonse Patamob",
    "Amadeus Dansavoiturehacausedeschiens",
    "Amanda Bleu (Amandable)",
    "Amandine Ozaur",
    "Amar Di",
    "Ambroise Bienlepetit",
    "Amhed Amet Le Couvert",
    "Amour Hire De Rire",
    "Amédé Bu",
    "Amélie Vapavitmélivaloin",
    "André Céouver",
    "André Daizartistte",
    "André Naline",
    "Andy Capé",
    "Angèle Fermlaporte",
    "Anna Tomie",
    "Anna-Lise Du Rine",
    "Anne Héantie",
    "Anne-Corinne Ptitghoute",
    "Annie Mâle",
    "Annie Versaire",
    "Annie-Zette Auffray",
    "Aphonse Kelpeuv",
    "Ariete Bordeauxchesnel",
    "Armand Bandouillère",
    "Armand Talo",
    "Armelle Couvert",
    "Astérix Épéril",
    "Aubin Sahalor",
    "Aude Hébussavabien",
    "Aude Javel",
    "Aude Vesselle",
    "Aurore Boréale",
    "Aurore Polaire",
    "Aurélie Biencequetaécri",
    "Axel Ère",
    "Barack Afritt",
    "Barbara Dégout",
    "Bart Haba",
    "Bernadette Dejeu",
    "Bernard Tichaut",
    "Berthe Zéprofit",
    "Beth Rave",
    "Bianca Lamine",
    "Bienvenue Parminou",
    "Bill Hattérahl",
    "Blanche Adéçin",
    "Bob Ho",
    "Bowie Ken Éalain Die",
    "Bowie Kent",
    "Brice Glace",
    "Burt Hatartynn",
    "Camille Onette",
    "Camille Zole",
    "Candice Et De Fondouze",
    "Candy Raton",
    "Candy Tu",
    "Carla Parolédor",
    "Charles Ottofraize",
    "Cicéron Cépacaré",
    "Claire De Lune",
    "Claire Hyère",
    "Claire Hénett",
    "Claire Laplace",
    "Claire Obscure",
    "Claire Voyance",
    "Clemence Dutribunal",
    "Clémence De Dieu",
    "Clément Tine",
    "Colette Stérole",
    "Cyrielle Épatriste",
    "Cyril Hique",
    "Cécile En Cieux",
    "Cécile Hon",
    "Cécile Houinkça",
    "Céline Évitable",
    "Daisy D. Malplacé",
    "Daisy Des Rata",
    "Daisy Dyossi",
    "Daisy Rable",
    "Dan Delion",
    "Dick Técenfote",
    "Djamal Alatête",
    "Djamal Digéré",
    "Djamal Dormi",
    "Djigaut Daniel",
    "Douglas O’Chocola",
    "Eddy Don Marcel",
    "Eddy Scylla",
    "Edmond Camionarentrer",
    "Edmond Fils",
    "Edmond Grec",
    "Edmond Prochain",
    "Edmond Saintmichel",
    "Ella Bienvu",
    "Ella Danloss",
    "Ella De Bonzieux",
    "Ella Lagingrat",
    "Ella Lapêche",
    "Elmer Itmieu",
    "Elsa Dorsa",
    "Elsa Rose Laure Annie Versaire",
    "Elvira Goche",
    "Elvire Horouge",
    "Elvis Cruxiforme",
    "Eléonor Marolex",
    "Emma Bienhu",
    "Emma Paradé",
    "Emmanuelle De Classe",
    "Eric Hochet",
    "Esmée Valda",
    "Estelle Man Important",
    "Estelle Oussacopine",
    "Eva Porée",
    "Eva Sion",
    "Eve Vitlézembrouilles",
    "Farid Hannibal (Farine Animale)",
    "Fidel Assonmek",
    "Fidèle Annamour",
    "Fidèle Hamoimème",
    "Firmin Dustriel",
    "Fred Voyage",
    "Félix Avant Lehigrek",
    "Gael Épahintéréssé",
    "Garcin Lazare",
    "Gaspard Alizan",
    "Gaspard Fait",
    "Gemal Allesse Thomas",
    "Geoffroy Denledo",
    "Georgette Tousskjebouf",
    "Gerard Menvuça",
    "Gilbert Monlatin",
    "Gilles Haidesovetaj",
    "Gilles Parbal",
    "Gilles S. Desplumes",
    "Gina Bricot Épêche",
    "Ginette Toyélévécé",
    "Guillaume Tinné",
    "Guy De Michelin",
    "Guy Don De Course",
    "Guy Tar",
    "Guy Yiotine",
    "Gédéon Groidenmabaignoire",
    "Gérard Issime",
    "Gérard Manvussa",
    "Gérard Mendufric",
    "Gérard Menfaim",
    "Habib Oché",
    "Hakim Membien",
    "Hans Cenhalan",
    "Hans Kim Koncern",
    "Harry Cover",
    "Harry Stote",
    "Hassan Cehef",
    "Hassan Glier",
    "Helmut Tardeellepique",
    "Henri Amédé Pan",
    "Henri Cochet",
    "Henri Gole",
    "Henri Hencor",
    "Henri Poste",
    "Henri Stourne",
    "Hercule Danlapante",
    "Hippolyte Ize Le Débat",
    "Hyppolite Hic",
    "Hésotte Eric",
    "Igor Dehors",
    "Ima Geley",
    "Inès Alamaternité",
    "Irénée Ledivinenfant",
    "Isabelle Parleurnom",
    "Ivan Desmuguets",
    "Jacques Couche",
    "Jacques Célert",
    "Jacques Ouzi",
    "Jacques Sonne",
    "Jacques Use",
    "Janette Pafin",
    "Jean Balle Toultan",
    "Jean Bambois",
    "Jean Bave",
    "Jean Bonboeur",
    "Jean Bonnaud",
    "Jean Civabimé",
    "Jean Némard",
    "Jean Philémon Pull",
    "Jean Prendnote",
    "Jean Registre",
    "Jean Reprendraisbienunptitouimerci",
    "Jean Rigole",
    "Jean Tanrien",
    "Jean Titouplin",
    "Jean Édeu",
    "Jean Éhenvumil",
    "Jean-Aymard",
    "Jean-Loup Raipas",
    "Jean-Marie Deux",
    "Jeanne Dmépassa",
    "Jeanne Écassé",
    "Jeff Hun",
    "Jenifer Rien",
    "Jennifer Arepassé",
    "Jerry Kan",
    "Jessica Net O’Frigo",
    "Jessica Niche",
    "Jessica Trizévit",
    "Jim Haimongrindsel",
    "Jo Bar",
    "John Duff",
    "John Veuplu",
    "Juda Nanasse Éjudas Bricot",
    "Jules Hule",
    "Julie Danstépensé",
    "Julien Ternette",
    "Julienne De Légum",
    "Justin Calva",
    "Justin Ptipeu",
    "Justine Ptitghoute",
    "Jérémy Ade",
    "Jérémy Unmantopourlivère",
    "Karl Amel Mou",
    "Karl L’Âge",
    "Kelly Diossi",
    "Kelly Diote",
    "Khaled Ossecour",
    "Khan Hisch",
    "Lady Commandement",
    "Lara Masse",
    "Lara Suretil En Amour",
    "Lara Tatouille",
    "Larry Golade",
    "Lary Bambel",
    "Laure Brille",
    "Laure Dure",
    "Laure Plaquée",
    "Laure Tiblanche",
    "Laure Voirrémerci",
    "Laure Édubois",
    "Laure Éyencoin",
    "Laure-Ange Ajus",
    "Laurent Gina",
    "Laurent Ginette",
    "Laurent Houtan",
    "Lazare Fébienléchose",
    "Lenny Fiant",
    "Line Ottension",
    "Line Évitable",
    "Lola Mouille-Les-Sec",
    "Louis Dort",
    "Lucie Ditée",
    "Lucie Fer",
    "Lucien Cien À Sa Mémère",
    "Lydie Commandements",
    "Lydie O’Duvillage",
    "Léon Dit",
    "L’Agent Beudeboit",
    "L’Esmée Basket",
    "Marc Des Points",
    "Marc Débutt",
    "Marc À Saint",
    "Marie Age",
    "Marie Tim",
    "Marie Vière",
    "Marie-Ange Pluvieux, Marie-Ange Heureux",
    "Marjorie Devault",
    "Marthe Él’Entête",
    "Martial Lacour",
    "Martine De Pin Beurré",
    "Mathilde Ivertement (M’A-T-Il Dit Vertement)",
    "Matéo Porte",
    "Maude Cambronne",
    "Maude Erateur",
    "Maude Ysoitil",
    "Max Hymôme",
    "Melanie Zetofrais",
    "Micheline Étrain",
    "Mick Emmaus",
    "Milène Micoton",
    "Modeste Men",
    "Modeste Oma",
    "Moshé Rimonamour (Mon Chéri …)",
    "Médhi Khaman",
    "Mélanie Dansmonverre",
    "Mélusine Enperte",
    "Nadine Amo",
    "Nadège Avudotre",
    "Nestor Nade",
    "Nicolas Nihorangina",
    "Nordine Ateur",
    "Norma Leman",
    "Olive De Messe",
    "Omar Et Clovis (Homard Écrevisse)",
    "Otto Graf",
    "Ovide La Tinette",
    "Ovide Lapoubelle",
    "Pacôme Les Autres",
    "Pacôme Toullemonde",
    "Pacôme-Aude La Vielle",
    "Parfait Temmen",
    "Paris Si",
    "Pat Hibulaire",
    "Pat Houproch",
    "Pat Redway (Pas Très Doué)",
    "Pat Regret",
    "Pat Réloin",
    "Paterne Hité",
    "Paul Chtron",
    "Paul Et Mick Ou Mickey",
    "Paul Hémique",
    "Paul Ochon",
    "Paul Ution",
    "Paula Roïd",
    "Percy Flage",
    "Perrine Héale",
    "Phil Alapatte",
    "Phil Trahuile",
    "Philémon Banylon",
    "Philémon Codesecret",
    "Pierre Domsbale",
    "Pierre Kiroul",
    "Pierre Ponce",
    "Pit Za",
    "Prosper Hytté",
    "Prudence Est Maire De Sûreté",
    "Pénélope Solette",
    "Quentin Gendarmerit",
    "Rabbi Boché",
    "Ramon La Cheminée",
    "Ray Ponse",
    "Remy Fasol",
    "René Kikoul",
    "Renée De Cécendre",
    "Renée Sens",
    "Rhama Çagescolaire",
    "Richard Dasso",
    "Rob Otique",
    "Rod Hanien",
    "Roland Dégouts",
    "Roméo Frigo",
    "Rony Vienplus",
    "Rose Des Vents",
    "Règis Sœur Desimpôts",
    "Sacha Hutte",
    "Sacha Touille",
    "Salim Bienléongle",
    "Sam Di C. Lafette",
    "Sam Eugène",
    "Sam Gratte",
    "Sam Hovar",
    "Sam Lécasse",
    "Sam Pique",
    "Samantha Lo",
    "Samira Bien",
    "Samson Éssan-Image",
    "Sandra De Desssous",
    "Sandra De Lit",
    "Sandra Nicouverture",
    "Sandy Ferrance",
    "Sandy Kilo",
    "Sandy Manché",
    "Sandy Métrehé",
    "Sarah Croche",
    "Sarah Fréchit",
    "Sarah Masse",
    "Sarah Pelle",
    "Sarah Pelpu",
    "Sarah Sion",
    "Sarah Tattine",
    "Sarah Vigote",
    "Sarah Visseuse",
    "Scott Ché",
    "Serge Oin",
    "Sheila Lutfinale",
    "Sheila Zizanie",
    "Sim K. Mil",
    "Solange Eulure",
    "Sylvain Ebon",
    "Sylvain Étiré",
    "Sylvie Cékilépamor",
    "Sylvie Encorasommle",
    "Sylvie Ragesurvient Jevire",
    "Sébastienne Touseul",
    "Séverine De Confiture",
    "Tanguy Yadlavi-Yadlespoir",
    "Tarek Tifié",
    "Ted Bouvamechercher Unebière",
    "Teddy Nainportekoi",
    "Terry Dicule",
    "Terry Kiki",
    "Tex Agère",
    "Thibault Timeplé",
    "Thierry Chmonfils",
    "Thierry Golo",
    "Thomas Toketchup",
    "Thomas Waques",
    "Théa Louest",
    "Théophile Éhontlobe",
    "Thérèse Ponsabledumatos",
    "Tim Hagine",
    "Tom De Savoie",
    "Tom Hawack",
    "Tom Égérie",
    "Tristan Amour",
    "Vicky Népamort",
    "Vishnou Lapaix",
    "Vivien Chezmoi",
    "Xavier K. Paétrela",
    "Yann Akepourlui",
    "Yoland Gingras",
    "Yvan Dubois",
    "Yvan Pèrémère",
    "Yvan Tou Hassan Souh",
    "Yves Atrovite",
    "Yves De La Salle (De La Salle Yves)",
    "Yves Héron",
    "Yves Vapabien",
    "Yves Vapartout",
    "Yvon Enbavé",
    "Yvon Lavallée",
    "Yvon Tremblay",
    "Zinedine Pacesoir",
    "Èva Skacélagueul",
    "Ève Heille Des Sens",
    "Édith Orial",
    "Élie Coptère",
    "Élise Émoi",
    "Éléonore Iléosud",
    "Éva Kuéleslieux",
  ]

// TODO : trier dans l'ordre alpha
const namesNSFW =[
    "Anne Halle",
    "Apiss Dedan",
    "Arthur Lut",
    "Arétha Connerie",
    "Berthe Alors",
    "Chirac Côté",
    "Clint Horris",
    "Denis Chon",
    "Dereck Tom",
    "Edgard Atéfesse",
    "Edmond Cul C. Du Poulet",
    "Ella Léssein Halerre",
    "Eva Lavétoncul",
    "Eva Pisser",
    "Firmin Peutagueule",
    "Gérard Menjoui",
    "Héléna Du Mondaubalcon",
    "James Tonptiku",
    "Jean-Phil Monslip",
    "Jeff Hépipioli",
    "Jessica Potanglaise",
    "Khan Jepet Jehpu",
    "Lorie Fice",
    "Marie Rouana",
    "Octave Ergebelle",
    "Odile Hatmoilarate",
    "Omer Dalors",
    "Roland Culé",
    "Sam Troulefion",
    "Simon Cussonet",
    "Simon Cussonetorelheur",
    "Sylvie Bromasseur",
    "Yvon Et Jacques Kulé",
]

const allnames = (namesSFW+namesNSFW).split(",");